name: PHPCodeSniffer

on:
  push:
    branches: [ "main","jetstream","filamentphp" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main","jetstream","filamentphp" ]

jobs:
  phpcodesniffer:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.2","8.3"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring,  intl,ext-intl,ext-zip
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist
      - run: ./vendor/bin/phpcs -h
      - run: ./vendor/bin/phpcbf -h
