name: PHPmd

on:
  push:
    branches: [ "main","jetstream","filamentphp" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main","jetstream","filamentphp" ]

jobs:
  phpmd:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.2","8.3"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring,  intl,ext-intl,ext-zip
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist
      - run: ./vendor/bin/phpmd app github phpmd.ruleset.xml
      - run: ./vendor/bin/phpmd app html phpmd.ruleset.xml --report-file result.html
      - run: ./vendor/bin/phpmd app xml phpmd.ruleset.xml --report-file result.xml

