name: Psalm

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  psalm:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.2","8.3"]

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist
      - run: php ./vendor/bin/psalm --threads=2 --output-format=github --report=results.sarif
