name: Psalm

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  psalm:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.2","8.3"]

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist
      - run: php ./vendor/bin/psalm --threads=2 --output-format=github --report=results.sarif
